name: Deployment
on:
  push:
    branches:
      - production
      
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x.x'
      - run: docker compose down
      - run: docker compose build app
      - run: docker compose up -d
    
